[io]
dataDir = "data"
outDirSuffix = "out"
genDirSuffix = "gen"

[main] # Defaults for minimum of 128x128 resolution
strokeWidth = 1
kernelSize = 9

[generator] # Defaults for 1024x1024 with 20 sections
strokeWidth = 60
step = 10.0
fov = 0.25
initialBound = 0.25
momentumFactor = 0.8
tensionFactor = 1.0
repelFactor = 0.4
imperfectionFactor = 0.1
